/*
 * Copyright (c) 2026 egoge.com. All rights reserved.
 */
package com.egoge.ai.atlas.processor.generator;

import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.tools.Diagnostic;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.Writer;

/**
 * Generates {@code META-INF/ai-atlas/api-version.properties} containing
 * compile-time version configuration. Runtime modules can read this to
 * detect compile-time/runtime config mismatch.
 */
public final class ApiVersionPropertiesGenerator {

    private static final String RESOURCE_PATH = "META-INF/ai-atlas/api-version.properties";

    private ApiVersionPropertiesGenerator() {}

    public static void generate(String apiBasePath, int apiMajor,
                                Filer filer, Messager messager) {
        try {
            var resource = filer.createResource(StandardLocation.CLASS_OUTPUT, "", RESOURCE_PATH);
            try (Writer writer = resource.openWriter()) {
                writer.write("# Generated by ai-atlas processor\n");
                writer.write("api.major=" + apiMajor + "\n");
                writer.write("api.basePath=" + apiBasePath + "\n");
            }
            messager.printMessage(Diagnostic.Kind.NOTE,
                "[ai-atlas] Generated: " + RESOURCE_PATH);
        } catch (IOException e) {
            messager.printMessage(Diagnostic.Kind.ERROR,
                "[ai-atlas] Failed to write " + RESOURCE_PATH + ": " + e.getMessage());
        }
    }
}
