/*
 * Copyright (c) 2026 egoge.com. All rights reserved.
 */
package com.egoge.ai.atlas.runtime.security;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.MethodParameter;
import org.springframework.http.MediaType;
import org.springframework.http.converter.HttpMessageConverter;
import org.springframework.http.server.ServerHttpRequest;
import org.springframework.http.server.ServerHttpResponse;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.servlet.mvc.method.annotation.ResponseBodyAdvice;

import javax.annotation.processing.Generated;
import java.util.Collection;

/**
 * Response body advice that verifies generated REST controllers only
 * return AI-ATLAS generated DTOs (annotated with {@code @Generated("com.egoge.ai.atlas.processor")}).
 *
 * <p>If a raw entity (non-DTO) is returned from a {@code /api/v1/} endpoint,
 * a warning is logged. This acts as a runtime safety net ensuring PII-safe
 * DTOs are always used in generated API responses.
 */
@ControllerAdvice
public class DtoResponseBodyAdvice implements ResponseBodyAdvice<Object> {

    private static final Logger log = LoggerFactory.getLogger(DtoResponseBodyAdvice.class);
    private static final String GENERATED_API_PREFIX = "/api/v1/";

    @Override
    public boolean supports(MethodParameter returnType, Class<? extends HttpMessageConverter<?>> converterType) {
        // Only check responses from generated controllers
        Class<?> declaringClass = returnType.getDeclaringClass();
        Generated generated = declaringClass.getAnnotation(Generated.class);
        return generated != null && "com.egoge.ai.atlas.processor".equals(generated.value()[0]);
    }

    @Override
    public Object beforeBodyWrite(Object body, MethodParameter returnType,
                                  MediaType selectedContentType,
                                  Class<? extends HttpMessageConverter<?>> selectedConverterType,
                                  ServerHttpRequest request, ServerHttpResponse response) {
        if (body == null) {
            return null;
        }

        Object toCheck = body;
        if (body instanceof Collection<?> collection && !collection.isEmpty()) {
            toCheck = collection.iterator().next();
        }

        if (toCheck != null && !isGeneratedDto(toCheck.getClass())) {
            log.warn("[ai-atlas] Response from {} contains non-DTO type '{}'. "
                            + "Generated REST controllers should return AI-ATLAS DTOs for PII safety.",
                    request.getURI().getPath(), toCheck.getClass().getName());
        }

        return body;
    }

    private static boolean isGeneratedDto(Class<?> clazz) {
        Generated generated = clazz.getAnnotation(Generated.class);
        if (generated != null) {
            for (String value : generated.value()) {
                if ("com.egoge.ai.atlas.processor".equals(value)) {
                    return true;
                }
            }
        }
        // Records generated by AI-ATLAS are always @Generated — if it's a record
        // without @Generated, it's likely a user type
        return false;
    }
}
