/*
 * Copyright (c) 2026 egoge.com. All rights reserved.
 */
package com.egoge.ai.atlas.runtime.autoconfigure;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Properties;

/**
 * Detects compile-time/runtime version configuration mismatch at startup.
 *
 * <p>Reads {@code META-INF/ai-atlas/api-version.properties} from the classpath
 * (generated by the annotation processor in Phase 3) and compares against the
 * runtime {@link AgenticProperties.Api} configuration. Mismatches are emitted as
 * structured WARNING log messages — not exceptions — so that legitimate staged
 * rollout scenarios are not blocked.
 */
public final class VersionMismatchDetector {

    private static final Logger log = LoggerFactory.getLogger(VersionMismatchDetector.class);
    private static final String PROPERTIES_PATH = "META-INF/ai-atlas/api-version.properties";

    private VersionMismatchDetector() {}

    /**
     * Checks for compile-time/runtime version configuration mismatch.
     * Called once at startup by {@link AgenticAutoConfiguration}.
     *
     * @param runtimeApi the runtime API configuration to compare against
     */
    public static void check(AgenticProperties.Api runtimeApi) {
        check(runtimeApi, VersionMismatchDetector.class.getClassLoader());
    }

    /**
     * Checks for compile-time/runtime version configuration mismatch using the given classloader.
     * Package-private to allow test injection of custom classpath resources.
     *
     * @param runtimeApi  the runtime API configuration to compare against
     * @param classLoader classloader to use for resource lookup
     */
    static void check(AgenticProperties.Api runtimeApi, ClassLoader classLoader) {
        var resource = classLoader.getResource(PROPERTIES_PATH);
        if (resource == null) {
            log.debug("[ai-atlas] No {} found on classpath — skipping version mismatch check",
                    PROPERTIES_PATH);
            return;
        }
        try (var is = resource.openStream()) {
            var props = new Properties();
            props.load(is);
            int compileMajor = Integer.parseInt(props.getProperty("api.major", "1"));
            String compileBasePath = props.getProperty("api.basePath", "/api");

            if (compileMajor != runtimeApi.getMajor()) {
                log.warn("[ai-atlas] Version mismatch: compile-time api.major={} "
                        + "but runtime ai.atlas.api.major={}. "
                        + "Generated artifacts were built for v{} — "
                        + "runtime behavior may be inconsistent.",
                        compileMajor, runtimeApi.getMajor(), compileMajor);
            }
            if (!compileBasePath.equals(runtimeApi.getBasePath())) {
                log.warn("[ai-atlas] Base path mismatch: compile-time api.basePath='{}' "
                        + "but runtime ai.atlas.api.base-path='{}'. "
                        + "Generated REST controllers use '{}' — "
                        + "requests may not reach generated endpoints.",
                        compileBasePath, runtimeApi.getBasePath(), compileBasePath);
            }
        } catch (Exception e) {
            log.debug("[ai-atlas] Failed to read {}: {}", PROPERTIES_PATH, e.getMessage());
        }
    }
}
